const lead=(title,site,stat,entry,document)=>({title,site,stat,entry,document});
const mission=(id,title,requires,brief,leads,question,answers,correct,explanation,publicEnding,quietEnding,optional=false)=>({id,title,requires,brief,leads,question,answers,correct,explanation,publicEnding,quietEnding,optional});
export const CHAPTER_FIVE={
 number:5,id:'ashes',title:'Asche im Dockring',hub:'h9_coordination',targetMinutes:[300,360],
 premise:'Nach der Warnung ist Helios-9 noch da. Doch Menschen verschwinden aus Evakuierungslisten, Schutzgelder wechseln die Besitzer und jemand benutzt die Rettung, um alte Schulden zu begleichen. Mara sucht ihren Bruder nicht mehr auf einer Fähre, sondern zwischen widersprüchlichen Akten.',
 sites:{
 h9_coordination:['Helios-9 · Koordinationsraum','Unter dem alten Fahrplan hängen jetzt Papierlisten. Auf jede kommt eine andere Handschrift.'],
 h9_ward:['Helios-9 · Notstation','Eine Pflegerin schreibt Namen auf Klebeband. Die elektronischen Armbänder sind ausgegangen.'],
 h9_records:['Helios-9 · Registerhalle','Ausgedruckte Evakuierungslisten bedecken die Kontrollpulte. Manche Namen sind mehrfach durchgestrichen.'],
 h9_concourse:['Helios-9 · Wohnring','Zwischen Schlafmatten stehen Ladekabel und Wasserkanister. Niemand hat den richtigen Anschluss.'],
 h9_maintenance:['Helios-9 · Lastenschächte','Hinter den Leitungen bewegen sich Lampen. Die Instandhaltung arbeitet seit zwei Schichten ohne Ablösung.'],
 h9_terminal:['Helios-9 · Fährterminal','Die Anzeigetafel meldet pünktliche Abfahrten für Fähren, die nie am Steg standen.'],
 h9_exchange:['Helios-9 · Tauschhalle','Batterien liegen neben Fotografien. Beides wird gebraucht, nur eines hat einen festen Preis.'],
 h9_council:['Helios-9 · Ratsfoyer','Ein Sicherheitsmann lässt Flüchtlinge eintreten und Kameras draußen warten.']
 },
 missions:[
 mission('manifest','Fähre zwölf',[],`Mara hat die Nachricht ihres Bruders siebzehnmal abgespielt. Auf Fähre zwölf sei er sicher, sagte er. Die Ankunftsliste kennt seinen Namen nicht.

Im Koordinationsraum zeigt eine Freiwillige auf drei Stapel. „Abfahrt, Ankunft, Behandlung. Wenn Sie nur einen davon lesen, finden Sie entweder alle oder niemanden.“

Mara legt ihr Terminal hin. „Er heißt Iven Sato. Nicht nur Sato. Nicht Patient 84.“`,[
 lead('Eine Nummer ohne Namen','h9_ward','charisma','Die Pflegerin will erst wissen, ob du Angehörige suchst oder jemanden abholen sollst. Hinter ihr beginnt ein Monitor zu piepen. Du kannst helfen, den Wagen beiseitezuschieben, bevor du weiterfragst.','Das Behandlungsblatt von Patient 84 vermerkt einen Armbruch und die Ankunft mit einem Frachtaufzug. Der Eintrag wurde vor dem Ablegen von Fähre zwölf erstellt. Die Kleidung wurde an die Instandhaltung zurückgegeben. Am unteren Rand hat jemand „I. Sato — wach“ ergänzt.'),
 lead('Eine Fähre mit zwei Listen','h9_records','intelligence','Die Registrarin bindet die Papierstapel mit unterschiedlich gefärbten Schnüren zusammen. „Weiß ist übertragen. Blau hat noch jemand in der Hand gehabt.“ Die Liste der Zwölf trägt beide Farben.','Die Abfahrtsliste kopierte eine vorläufige Buchung. Das tatsächlich gescannte Armband fehlt. Eine automatische Nachricht „an Bord“ wurde bei Buchung versendet, nicht beim Einstieg. Die Ankunftsliste ist korrekt; die ursprüngliche Bestätigung war es nicht.'),
 lead('Die abgeschnittene Verbindung','h9_terminal','tech','Der Servicetechniker lässt dich an den stillgelegten Sender. Im Lautsprecher ist Ivens letzter Satz kaum zu verstehen, weil eine Durchsage darüberliegt. Du trennst beide Kanäle.','Unter der Ansage sagt Iven: „Ich nehme den Lastenweg. Da kommt noch jemand nicht mit.“ Der Sender gehört zu Schacht C, zwei Ebenen unter dem Fährsteig. Sein letztes Signal kam von der Station, nicht aus einer Fähre.')
 ],'Welche Spur führt tatsächlich zu Iven?', ['Fähre zwölf ist heimlich umgekehrt.','Iven blieb für eine Rettung im Lastenschacht zurück.','Die Notstation hat einen fremden Namen erfunden.'],1,'Buchung war nicht Einstieg. Behandlungszeit und Sendestandort führen unabhängig zum Lastenschacht.',
 'Mara lässt den Suchaufruf mit Ivens vollständigem Namen verbreiten. Weitere Angehörige melden dieselbe falsche Bordbestätigung. Aus einer privaten Suche wird ein Problem, das die Leitstelle nicht mehr weglegen kann.',
 'Du gibst Mara die verifizierte Spur, bevor ihr andere Namen nennt. Sie ruft die Schachtmannschaft an. „Ich weiß jetzt, wo ich suchen muss“, sagt sie. Erst danach setzt sie sich.'),
 mission('water','Der Preis eines Bechers',[],`Vor einer Wasserstelle hält eine Frau eine Münze hin. Der Mann am Ventil schüttelt den Kopf; die Münze gilt seit gestern nicht mehr.

Die Frau steckt sie weg, ohne zu streiten. Ihr Kind wartet mit zwei Bechern. Der kleinere ist für jemanden, der nicht in der Schlange steht.

Die Versorgung meldet volle Tanks. Irgendwo zwischen Tank und Becher wird Wasser knapp.`,[
 lead('Ein unauffälliges Ventil','h9_maintenance','tech','Eine Mechanikerin hat das Siegel am Druckregler fotografiert, bevor sie es öffnet. Sie reicht dir das Gerät. „Wenn nachher jemand behauptet, ich wäre es gewesen, erinnern Sie sich daran.“','Der Regler ist auf Nachtverbrauch begrenzt, obwohl sich die Belegung verdreifacht hat. Die Änderung stammt aus einem gültigen Wartungsauftrag. Als Begründung steht „Leckverdacht“, aber kein Messwert wurde angehängt.'),
 lead('Die neue Marke','h9_exchange','perception','Unter einer Plane werden Wasserberechtigungen gegen Batterien verkauft. Die Marken sehen amtlich aus. Eine Verkäuferin zeigt dir bereitwillig die Rückseite: Dort steht eine Firma, die Pumpen wartet.','Die Firma erhielt den Auftrag zur Untersuchung des vermeintlichen Lecks. Sie lässt sich gleichzeitig die knappe Ausgabe in privaten Marken bezahlen. Lieferungen an ihre eigenen Lager wurden von der Begrenzung ausgenommen.'),
 lead('Der Kanister im Wohnring','h9_concourse','charisma','Ein Hausmeister hat die Durchflusszeiten der letzten Tage auf die Wand geschrieben. „Ich bin kein Ingenieur“, sagt er. „Aber ich weiß, wie lange ich für zehn Liter stehe.“','Der Durchfluss sank unmittelbar nach der Auftragserteilung. Weder Tankstand noch Messung im Wohnring zeigen einen Verlust. Die Begrenzung erzeugt den Mangel, den die Wartungsfirma angeblich behebt.')
 ],'Was verursacht die Knappheit?', ['Ein technischer Engpass wurde künstlich angeordnet.','Die Bewohner verbrauchen heimlich das Dreifache.','Ein beschädigter Tank verliert Wasser ins All.'],0,'Volle Tanks, fehlende Leckwerte und Ausnahmen für Firmenlager belegen eine angeordnete Drosselung.',
 'Die Wand mit den Messzeiten wird zum Aushang. Die Ratsverwaltung hebt die Drosselung auf. Der Hausmeister verteilt keine Marken; er dreht das Ventil auf und lässt die Schlange selbst entscheiden, wer zuerst dran ist.',
 'Du zwingst die Firma zur Freigabe der Versorgung, ohne die Beschäftigten am Ventil bloßzustellen. Die privaten Marken verschwinden am selben Abend. Wer dahintersteht, bleibt nur in eurer Akte.'),
 mission('signal','Die zweite Warnung',['manifest'],`Eine weitere Nachricht verbreitet sich: Der Wohnring werde in einer Stunde abgeschaltet. Niemand nennt einen Absender, aber alle kennen jemanden, der ihn kennt.

Lyra liest den Text und legt ihn neben eure ursprüngliche Warnung. Ein Satz ist identisch. Das macht die neue Nachricht glaubwürdig. Es macht sie nicht wahr.`,[
 lead('Das wiederverwendete Paket','h9_records','tech','Ein Archivterminal speichert die erste Fassung der Nachricht. Jede spätere Weiterleitung hat den Anhang verloren. Im Original ist er noch da.','Die digitale Signatur bestätigt eure alte Warnung, nicht die neu angefügte Abschaltzeit. Der neue Absatz liegt außerhalb des signierten Bereichs. Ein gültiges Dokument wurde als Umschlag für eine falsche Meldung benutzt.'),
 lead('Ein Platz auf der nächsten Fähre','h9_terminal','charisma','Eine Disponentin nimmt Reservierungen auf, die nicht durch das normale System gehen. Sie zeigt dir die Reihenfolge ihrer Eingänge, statt Namen zu nennen.','Die ersten privaten Buchungen trafen vor der falschen Warnung ein. Alle kamen über denselben Vermittler. Er kaufte freie Plätze auf und erhöhte den Preis, nachdem der Wohnring in Panik geriet.'),
 lead('Das wartende Licht','h9_maintenance','tech','Am Abschaltpult hängen handschriftliche Kennzeichnungen an jeder Leitung. Der Ingenieur bietet an, sie einzeln mit dir durchzugehen. „Wenn Sie etwas finden, das in einer Stunde ausgeht, sagen Sie mir Bescheid.“','Es gibt keine geplante Abschaltung. Die Versorgung läuft auf zwei unabhängigen Einspeisungen. Eine Sicherheitsübung vom Vormonat hat dieselbe Uhrzeit wie die Falschmeldung, aber ein anderes Datum.')
 ],'Wie konnte eine falsche Meldung eure Signatur tragen?', ['Eure Schlüssel wurden vollständig kopiert.','Die Abschaltung ist echt, wird aber vertuscht.','Ein unsignierter Zusatz wurde an die echte Warnung angehängt.'],2,'Die Signatur endet vor dem Zusatz. Buchungszeiten und alter Übungsplan erklären Motiv und Material.',
 'Lyra veröffentlicht Original und manipulierte Fassung nebeneinander. Keine bloße Gegendarstellung: Jeder kann sehen, wo der neue Absatz beginnt. Die Warteschlange am Terminal wird langsamer, dann kürzer.',
 'Du lässt den Vermittler die überhöhten Buchungen zurücknehmen und schickst die technische Widerlegung an die Wohnräte. Die Menschen hören es von jemandem, der auch morgen noch neben ihnen wohnt.'),
 mission('lifts','Unter der Kabine',['manifest','water'],`Ivens Spur endet an einem Lastenaufzug. Die Kabine hängt fest zwischen zwei Ebenen. Auf dem Dach liegt ein Werkzeugkoffer, den Mara sofort erkennt.

Die Schachtmannschaft will die Bremse lösen. Mara fragt, ob sie sicher wissen, was unter der Kabine steht. Die Antwort dauert zu lange.`,[
 lead('Die Last unter dem Boden','h9_maintenance','perception','Du legst ein Mikrofon an die Führungsschiene. Zwischen den Bewegungen der Kabine klopft jemand dreimal zurück. Die Mannschaft stellt sofort jede Arbeit ein.','Unter der Kabine hat Iven eine Trage in einer Wartungsnische verkeilt. Zwei Menschen leben. Das Gegengewicht lastet auf dem Zugang; ein normales Lösen der Bremse würde die Nische verschließen.'),
 lead('Ein Plan mit einem fehlenden Strich','h9_records','intelligence','Die Bauzeichnung zeigt eine freie Nische. Mara fährt mit dem Finger über den Ausdruck. „Die haben da vor zwei Jahren eine Leitung gelegt. Ich habe die Rechnung gesehen.“','Der Nachtrag zur Leitung fehlt in der Rettungskopie. Die aktuelle Wartungszeichnung zeigt einen seitlichen Zugang über eine entlastbare Traverse. Er bleibt offen, wenn zuerst das Gegengewicht gesichert wird.'),
 lead('Die falsche Freigabe','h9_council','charisma','Der Einsatzleiter hat eine unterschriebene Freigabe in der Hand. Er hält sie dir hin, als könne Papier die Verantwortung leichter machen.','Die Freigabe basiert ausdrücklich auf der alten Bauzeichnung. Sie ist nicht gefälscht, aber ungültig für den jetzigen Aufbau. Der Leiter kann die Operation stoppen, sobald er den dokumentierten Nachtrag erhält.')
 ],'In welcher Reihenfolge kann die Bergung gelingen?', ['Bremse lösen, danach das Gegengewicht sichern.','Gegengewicht sichern, seitlichen Zugang öffnen, Menschen bergen.','Kabine belasten, damit sie in die Nische absinkt.'],1,'Die aktuelle Zeichnung und das Klopfsignal machen die Sicherung des Gegengewichts zum ersten notwendigen Schritt.',
 'Die Mannschaft führt die Bergung vor laufender Einsatzkamera durch. Iven fragt nach seinem Werkzeug, bevor er nach Mara fragt. Sie nimmt ihm diese Frage übel, während sie ihn umarmt.',
 'Ihr korrigiert den Plan im kleinen Kreis und gebt die neue Reihenfolge an jede Schachtmannschaft weiter. Iven kommt auf einer Trage heraus. Mara geht neben ihm und hält nur den Griff fest.'),
 mission('ledger','Eine offene Rechnung',['water'],`Kael erkennt den Namen einer Zwischenfirma auf einer Versorgungsliste. Zum ersten Mal behauptet er nicht, sie nur vom Hörensagen zu kennen.

„Die haben früher für Leute wie mich gerechnet“, sagt er. „Man verkauft nichts. Man verschiebt nur, wer wem etwas schuldet.“

Auf der Liste stehen jetzt Unterkunft und Notmedizin.`,[
 lead('Zwei Behandlungen, eine Rechnung','h9_ward','intelligence','Die Abrechnung führt dieselbe Medikamentencharge zweimal auf. Die Ärztin zeigt dir die leeren Packungen: Es gab keine zweite Lieferung.','Der Hilfsfonds und die Patienten wurden für dieselbe Behandlung belastet. Die Beträge sind einzeln plausibel, gemeinsam aber doppelt. Der Firmenvermerk trennt beide Bücher, damit kein Sachbearbeiter sie nebeneinander sieht.'),
 lead('Ein Mandat ohne Grenze','h9_council','charisma','Ein junger Jurist holt den ursprünglichen Notvertrag aus einer Mappe. Seine Notizen sind so dicht, dass die Ränder nicht mehr weiß sind.','Die Zwischenfirma durfte Vorauszahlungen abwickeln, nicht Schulden privater Patienten ankaufen. Eine Zusatzklausel wurde erst nach der ersten Behandlung eingefügt und rückdatiert.'),
 lead('Kaels alte Kennung','h9_exchange','tech','Kael gibt dir eine veraltete Zugangskennung und bleibt sichtbar neben dir stehen. „Wenn du das öffnest, stehe ich auch drin.“','Die Buchungsfolge zeigt, wann die Zusatzklausel eingepflegt wurde. Kaels alte Geschäfte stehen im selben unveränderlichen Journal. Die neuen Einträge lassen sich belegen, ohne seine früheren Schuldner zu veröffentlichen.')
 ],'Welcher Beleg widerlegt die Forderungen?', ['Die Kombination aus doppelter Charge und rückdatierter Vertragsklausel.','Kaels schlechte Meinung über die Firma genügt.','Jede Notfallrechnung ist grundsätzlich gefälscht.'],0,'Chargennummern belegen die Doppelbelastung; die unveränderliche Buchungsfolge widerlegt das Datum der Zusatzklausel.',
 'Die Betroffenen erhalten einen begründeten Widerspruch statt einer vagen Entschuldigung. Kael lässt seine Kennung sperren. „Das wird mich ein paar Türen kosten“, sagt er. Er fragt nicht, ob es nötig war.',
 'Du handelst die Streichung der unzulässigen Forderungen aus und sicherst das Journal für spätere Verfahren. Kaels alte Kontakte bleiben aus dem Aushang. Die Notpatienten müssen trotzdem nichts doppelt bezahlen.'),
 mission('trial','Zeugen ohne Bühne',['signal','ledger'],`Die Ratsverwaltung will eure Belege prüfen. Drei Zeugen haben zugesagt, zwei verlangen Schutz, einer verlangt Geld.

Eine Vorsitzende stellt Wasser auf den Tisch. „Wenn Sie eine gute Geschichte haben, gehen Sie zu den Nachrichten. Hier brauche ich etwas, das auch dann steht, wenn wir Ihnen nicht glauben.“`,[
 lead('Eine genaue Erinnerung','h9_concourse','charisma','Die Zeugin kennt jedes Wort einer Durchsage. Bei der Uhrzeit zögert sie. Du lässt die Pause stehen, statt sie mit einer Zahl zu füllen.','Ihre Erinnerung an den Wortlaut stimmt mit dem Mitschnitt überein. Die Uhrzeit stammt dagegen aus einem späteren Gespräch. Ihre Aussage ist für den Inhalt belastbar, nicht für den Zeitpunkt.'),
 lead('Der geschlossene Umschlag','h9_records','perception','Ein Kurier brachte eine Speichereinheit ohne Begleitschreiben. Das Siegel ist unbeschädigt, die Inventarnummer wurde jedoch überschrieben.','Die Einheit wurde nach dem Ereignis neu nummeriert. Das macht den Inhalt nicht automatisch falsch, unterbricht aber die Herkunftskette. Eine Kopie auf dem ursprünglichen System bestätigt nur zwei der vier Dateien.'),
 lead('Die bezahlte Aussage','h9_exchange','charisma','Der dritte Zeuge sagt offen, dass er eine Tagesgage möchte. Er kann nicht fehlen, ohne seinen Platz an der Ausgabe zu verlieren.','Die Zahlung ersetzt einen dokumentierten Verdienstausfall und hängt nicht vom Inhalt der Aussage ab. Seine Aussage wird durch unabhängige Lieferdaten gestützt. Bezahlung allein widerlegt sie nicht.')
 ],'Welche Zusammenstellung ist belastbar?', ['Nur die lauteste Aussage und alle Dateien vom Kurier.','Alle Erinnerungen als exakte Zeitstempel behandeln.','Bestätigten Wortlaut, zwei verifizierte Dateien und belegte Lieferdaten getrennt vorlegen.'],2,'Zuverlässigkeit hängt am jeweiligen Belegteil. Einschränkungen sichtbar zu machen stärkt die überprüfbare Aussage.',
 'Die Anhörung bleibt öffentlich, persönliche Adressen werden geschwärzt. Als die Vorsitzende die unsicheren Teile ausdrücklich benennt, hört der Raum zum ersten Mal wirklich zu.',
 'Die Zeugen werden einzeln angehört. Du bestehst darauf, dass die Einschränkungen im Protokoll bleiben. Das Ergebnis verliert Schlagzeilen, aber nicht seine Begründung.'),
 mission('grid','Die Stadt unter Spannung',['lifts','trial'],`Der Test ist ausgesetzt. Seine Einspeisung hängt noch immer am Netz. Ein Rat will sie sofort abtrennen, ein anderer warnt vor dem Ausfall der Notstation.

Mara liest die Prioritätenliste. „Hier ist alles lebenswichtig“, sagt sie. „Wer hat entschieden, dass es dieselbe Leitung bekommt?“`,[
 lead('Der gemeinsame Rückweg','h9_maintenance','tech','Auf dem Pult liegen drei sauber beschriftete Pläne. Eine Verbindung ist nur auf dem ältesten eingezeichnet. Der Elektriker erkennt sie, bevor du danach fragst.','Die Versuchsanlage und die Notstation teilen einen Rückleiter. Ein vollständiges Kappen vor der Umschaltung würde den medizinischen Notbetrieb unterbrechen. Die Trennung ist möglich, aber nicht in beliebiger Reihenfolge.'),
 lead('Eine Reserve, die niemand bestellt hat','h9_terminal','perception','Zwischen Frachtcontainern stehen mobile Strommodule, die angeblich auf Freigabe warten. Ihre Anzeige zeigt einen erfolgreichen Selbsttest.','Die Module reichen für die Notstation während der Umschaltung. Sie wurden aus Versicherungsgründen dem zivilen Einsatz entzogen, nicht wegen eines technischen Defekts. Die Ratsverwaltung kann sie anfordern.'),
 lead('Die Reihenfolge im Protokoll','h9_ward','intelligence','Die leitende Pflegerin hat jeden Ausfall der letzten Schicht notiert. Neben einigen Uhrzeiten stehen Namen statt Geräte.','Drei Beatmungsplätze brauchen eine bestätigte Ersatzversorgung vor jedem Eingriff. Nach dem Lasttest kann die Station auf die mobilen Module, danach der gemeinsame Rückleiter getrennt und zuletzt die Dauerleitung geprüft werden.')
 ],'Was ist der sichere erste Schritt?', ['Mobile Ersatzversorgung anfordern und unter Last bestätigen.','Die Versuchsanlage sofort samt Rückleiter abschalten.','Die Notstation auf die spätere Reparatur vertrösten.'],0,'Die bestätigte Ersatzversorgung muss vor der Trennung stehen. Ein verfügbarer Generator ist noch kein erprobter Ersatzbetrieb.',
 'Die Umschaltung wird öffentlich protokolliert. Als das Licht einmal flackert, bleibt die Notstation hell. Im Ratsfoyer beginnt jemand zu klatschen; die Elektriker hören es nicht.',
 'Ihr arbeitet mit einer kleinen Einsatzgruppe. Erst nach bestandenem Lasttest meldet Mara die Trennung. Die Pflegerin streicht drei Namen von ihrer persönlichen Ausfallliste.'),
 mission('mandate','Wer für Helios spricht',['grid'],`Die Station braucht mehr als eine gerettete Leitung. Eine Übergangsverwaltung soll entscheiden, wer Versorgung, Register und die nächsten Untersuchungen kontrolliert.

Niemand nennt sich gern eine Übergangsverwaltung. Alle bringen schon fertige Namenslisten mit.`,[
 lead('Die Unterschriften','h9_concourse','perception','Unterstützerlisten liegen auf einem Klapptisch. Einige Namen wurden von Angehörigen unterschrieben, andere erscheinen dreimal.','Nach Bereinigung unterstützen mehrere Wohnräte einen zeitlich begrenzten gemeinsamen Ausschuss. Keine einzelne Liste besitzt die behauptete Mehrheit. Doppelte Namen erklären den scheinbaren Vorsprung.'),
 lead('Das Firmenangebot','h9_council','intelligence','Helix bietet Personal, Technik und einen festen Zeitplan. Lyra liest nicht die erste Seite, sondern die Kündigungsklausel.','Das Angebot überträgt der Firma nicht nur Wartung, sondern die Hoheit über Messdaten. Ein Abbruch wäre nur nach Zustimmung derselben Firma möglich. Technische Hilfe und Entscheidungshoheit sind im Vertrag absichtlich gekoppelt.'),
 lead('Die unabhängige Prüfstelle','h9_records','charisma','Eine Gruppe erschöpfter Registerkräfte bietet an, die Übergangsentscheidungen nachvollziehbar zu halten. Sie verlangen weniger Macht, als die anderen ihnen zutrauen.','Die Prüfstelle kann Daten veröffentlichen und Fehler dokumentieren, aber keine Versorgung übernehmen. Sie eignet sich als Kontrolle eines Ausschusses, nicht als alleinige Regierung.')
 ],'Welche Struktur trennt Betrieb und Kontrolle?', ['Helix darf die eigenen Daten abschließend beurteilen.','Ein befristeter ziviler Ausschuss mit unabhängiger Prüfstelle.','Die Prüfstelle soll ohne Personal die gesamte Versorgung führen.'],1,'Betrieb braucht ein Mandat; Kontrolle braucht Abstand zum Betreiber. Die bereinigten Listen tragen eine gemeinsame befristete Lösung.',
 'Der Ausschuss tritt mit einem Ablaufdatum an. Die Prüfstelle bekommt Kopien, keine Weisungen. Es ist keine glänzende Verfassung, nur etwas, das morgen überprüft werden kann.',
 'Du vermittelst einen begrenzten Betriebsvertrag und bestehst auf unabhängigen Kopien aller Messungen. Die Namen auf den Türen ändern sich langsamer als die Zuständigkeiten.'),
 mission('letters','Briefe, die nicht ankommen',[],`Im Wohnring werden Nachrichten an Menschen geschrieben, deren neue Adresse niemand kennt. Ein Junge bittet dich nicht, jemanden zu suchen. Er will nur wissen, ob sein Brief überhaupt abgeschickt wurde.`,[
 lead('Ein lokales Postfach','h9_records','tech','Das Terminal bestätigt jedes abgeschickte Schreiben mit einem grünen Haken. Du öffnest den genauen Status dahinter.','Der Haken bedeutet lokal gespeichert. Die Verbindung zum Relais fiel vor der ersten Nachricht aus. Keine einzige Nachricht wurde zugestellt; ebenso wenig wurde eine gelöscht.'),
 lead('Der verlegte Relaiskopf','h9_maintenance','perception','Eine Antennenleitung verschwindet hinter einer provisorischen Trennwand. Auf der anderen Seite lagert ein Rettungsteam seine Ausrüstung.','Beim Einrichten der Schlafbereiche wurde das Relais abgeschirmt. Es sendet gegen eine Metallplatte. Eine Verlegung um wenige Meter genügt, wenn die Freigabe des Raums vorliegt.'),
 lead('Die Rückmeldung','h9_concourse','charisma','Du fragst die Schreibenden, ob sie eine technische Bestätigung oder eine Antwort erwarten. Es ist nicht für alle dieselbe Frage.','Die Menschen wollen zwischen gespeichert, übertragen und beantwortet unterscheiden können. Eine ehrliche Statusanzeige verhindert falsche Hoffnungen auch dann, wenn niemand auf der anderen Seite antwortet.')
 ],'Was muss repariert werden?', ['Alle Briefe neu schreiben lassen.','Die Nachrichten ohne Rückmeldung löschen.','Relais verlegen und Speicherstatus von Zustellung trennen.'],2,'Die Briefe sind vorhanden. Verbindung und irreführende Anzeige sind die beiden getrennten Fehler.',
 'Die Schreibenden sehen erstmals echte Übertragungszeiten. Der Junge bleibt sitzen, bis sein Brief die Station verlassen hat. Auf eine Antwort wartet er später.',
 'Du lässt die Nachrichten nach Zustimmung der Schreibenden übertragen. Manche nehmen ihren Brief noch einmal zurück. Auch das ist eine Entscheidung, die der grüne Haken vorher nicht zugelassen hat.',true),
 mission('garden','Ein Stück Grün',[],`Eine Gärtnerin bewacht drei Kisten Setzlinge vor einer Luftschleuse. „Nicht für den Sauerstoff“, sagt sie, bevor du fragst. „Dafür sind es viel zu wenige. Für danach.“`,[
 lead('Die Salzspur','h9_maintenance','tech','Das Bewässerungswasser sieht klar aus. Die Ablagerung am Schlauch tut es nicht.','Eine Notleitung speist entsalztes Kühlwasser ein. Die Restkonzentration ist für technische Zwecke zulässig, für die jungen Pflanzen zu hoch.'),
 lead('Der letzte Filter','h9_exchange','charisma','Ein Händler bietet einen Trinkwasserfilter an und verspricht mehr, als auf der Verpackung steht.','Der Filter entfernt Partikel, nicht die gelösten Salze. Ein Ionentauscher aus dem Gewächshausbestand wäre geeignet, aber bisher ist nur seine Lagernummer bekannt.'),
 lead('Die inventarisierte Kiste','h9_records','intelligence','Im Register liegt die Kiste bei „Dekoration“, weil das Gewächshaus einmal zum Besucherbereich gehörte.','Der Ionentauscher ist vorhanden und nicht für medizinischen Bedarf reserviert. Eine korrigierte Zuordnung erlaubt seine Ausgabe, ohne ein lebenswichtiges Gerät umzuleiten.')
 ],'Was rettet die Setzlinge ohne falsches Versprechen?', ['Den passenden Ionentauscher aus dem freien Bestand verwenden.','Den Partikelfilter als Entsalzung verkaufen.','Die Pflanzen für die gesamte Sauerstoffversorgung einplanen.'],0,'Technischer Grenzwert ist kein Pflanzengrenzwert; Partikelfiltration entfernt die Salze nicht.',
 'Die ersten Kisten kommen in einen öffentlich zugänglichen Gang. Die Gärtnerin hängt kein Rettungsschild auf. Sie schreibt nur darunter, wann gegossen wird.',
 'Die Setzlinge bleiben vorerst im geschützten Lager. Ein paar Bewohner übernehmen die Pflege. Niemand muss erst eine Rede halten, bevor er etwas wachsen lassen darf.',true),
 mission('name','Kaels anderer Name',['ledger'],`Eine Frau erkennt Kael und nennt ihn bei einem Namen, den du noch nie gehört hast. Er verbessert sie nicht. Sie verlangt eine alte Lieferung zurück, die er angeblich nie gesehen hat.`,[
 lead('Die fehlende Kiste','h9_exchange','charisma','Die Frau kennt Inhalt und Gewicht der Kiste genau. Auf die Frage nach einem Beleg zieht sie eine zerknitterte Quittung hervor.','Die Lieferung bestand aus Ersatzprothesen. Kael nahm sie entgegen, die Zwischenfirma beschlagnahmte sie als Sicherheit. Die Empfängerin wurde nie informiert.'),
 lead('Ein geändertes Kürzel','h9_records','intelligence','Kaels Alias steht neben einer Empfangsbestätigung. Das spätere Ausgabekürzel gehört jemand anderem.','Kael hat die Annahme unterschrieben, aber nicht den Verkauf. Er wusste anschließend von der Beschlagnahmung und schwieg. Seine Verantwortung liegt im Verschweigen, nicht in einem belegten Weiterverkauf.'),
 lead('Der heutige Bestand','h9_ward','perception','Ein Orthopädietechniker gleicht die Seriennummern mit seinem Lager ab. Ein Teil der Lieferung liegt noch versiegelt dort.','Zwei Prothesen können zurückgegeben werden. Die dritte wurde nachweislich verwendet. Für sie ist Ersatz nötig; eine bloße Entschuldigung stellt die Lieferung nicht wieder her.')
 ],'Wofür muss Kael Verantwortung übernehmen?', ['Für jeden vermuteten Weiterverkauf ohne Beleg.','Für sein Verschweigen und eine konkrete Wiedergutmachung.','Für nichts, weil er die Kiste nicht selbst verkauft hat.'],1,'Die Dokumente trennen die ursprüngliche Unterschrift vom späteren Verkauf. Das belegte Verschweigen bleibt seine Entscheidung.',
 'Kael erklärt der Empfängerin selbst, was er wusste. Zwei Kisten gehen zurück, der Ersatz wird verbindlich zugesagt. Er benutzt diesmal seinen eigenen Namen.',
 'Du hilfst Kael, die Lieferung zu vervollständigen, ohne seinen Alias auf jeden Aushang zu setzen. Die Empfängerin entscheidet, ob sie nach der Übergabe noch mit ihm sprechen will.',true),
 mission('night','Eine Nacht ohne Durchsage',['lifts'],`Iven schläft in der Notstation. Mara sitzt daneben und hat nichts zu reparieren. Das macht sie unruhiger als der Alarm.

Sie bittet dich, drei Dinge zu holen: seinen Ausweis, einen alten Kopfhörer und die Nachricht, die ihr beide zu spät verstanden habt.`,[
 lead('Der Ausweis','h9_records','charisma','Die Registrarin hält den Ausweis zurück, bis ein Unterschied zwischen vermisst und geborgen dokumentiert ist.','Ivens Datensatz ist weiterhin als vermisst markiert. Ein bestätigter Bergungsnachweis korrigiert ihn, ohne die frühere Suchmeldung aus der Geschichte zu löschen.'),
 lead('Ein Kanal für sich','h9_exchange','tech','Der Kopfhörer hat ein gebrochenes Kabel. Der Verkäufer empfiehlt ein neues Gerät. Mara hatte ausdrücklich das alte genannt.','Eine einfache Reparatur reicht. Auf dem Bügel sind die Initialen der Geschwister eingeritzt. Der Wert hängt nicht an der Audioqualität.'),
 lead('Der ungekürzte Satz','h9_terminal','perception','Du hörst die Nachricht mit der bereinigten Tonspur. Nach dem vermeintlichen Ende folgt noch ein Atemzug.','Iven sagt: „Sag Mara nicht, sie hätte schneller sein müssen.“ Der Satz war vom Bestätigungston überdeckt. Er ändert nicht den Ablauf, aber die Geschichte, die Mara sich darüber erzählt.')
 ],'Was sollte Mara bekommen?', ['Eine bearbeitete Nachricht, in der alles leicht klingt.','Nur die technischen Bergungsdaten.','Den korrigierten Nachweis, den alten Kopfhörer und Ivens vollständige Worte.'],2,'Die drei Dinge haben unterschiedliche Aufgaben: Registrierung, Vertrautheit und eine Botschaft, die nicht umgeschrieben werden muss.',
 'Du gibst Mara alles und lässt die Tür offen. Später sitzt Iven wach im Bett. Die beiden streiten leise darüber, wer den Kopfhörer zuerst kaputtgemacht hat.',
 'Mara hört die Nachricht allein. Als sie herauskommt, steckt der reparierte Kopfhörer in ihrer Jacke. „Danke, dass du ihn nicht ersetzt hast“, sagt sie.',true)
 ]
};
